import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    productName: "Kookaburra Bat",
    price: "5841",
    mrp: "6499",
    offer: "10% OFF",
    categoryName: "BATS",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921594/CricBazzar%20Ecommerce/Cricket-bat_lwscgk.jpg",
    rating: "4.7",
    description: "Extreme power",
  },
  {
    _id: uuid(),
    productName: "New Balance Bat",
    price: "419",
    mrp: "2436",
    offer: "82% OFF",
    categoryName: "BATS",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1648872256/CricBazzar%20Ecommerce/TCPRO_1_large__09821.1644506752_wf8btt.jpg",
    rating: "2.5",
    description: "TC 450",
  },
  {
    _id: uuid(),
    productName: "New Balance Original",
    price: "32000",
    mrp: "40000",
    offer: "20% OFF",
    categoryName: "BATS",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1648872456/CricBazzar%20Ecommerce/Dc_1280__32141.1639678528_tw2aak.jpg",
    rating: "4.9",
    description: "TC PRO",
  },
  {
    _id: uuid(),
    productName: "Shadow Bat",
    price: "3250",
    mrp: "4000",
    offer: "19% OFF",
    categoryName: "BATS",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1648873926/CricBazzar%20Ecommerce/3T298103-shadow-bat__28013_aozgzv.webp",
    rating: "4.4",
    description: "Traning Bat",
  },
  {
    _id: uuid(),
    productName: "Leather Ball",
    price: "299",
    mrp: "699",
    offer: "57% OFF",
    categoryName: "BALLS",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921638/CricBazzar%20Ecommerce/cricket-ball_lco1zt.jpg",
    rating: "2",
    description: "Standard Size",
  },
  {
    _id: uuid(),
    productName: "SG Cricket Balls",
    price: "1050",
    mrp: "1500",
    offer: "30% OFF",
    categoryName: "BALLS",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1648872892/CricBazzar%20Ecommerce/aph_2011__37062.1604793276.600.600_category.original_ladagu.jpg",
    rating: "4.5",
    description: "Red Ball",
  },
  {
    _id: uuid(),
    productName: "Batting Gloves",
    price: "435",
    mrp: "750",
    offer: "42% OFF",
    categoryName: "PROTECTION",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921655/CricBazzar%20Ecommerce/cricket-gloves_jswvvp.jpg",
    rating: "3.8",
    description: "Large Size",
  },
  {
    _id: uuid(),
    productName: "Adidas Batting Pads",
    price: "1404",
    mrp: "1499",
    offer: "6% OFF",
    categoryName: "PROTECTION",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921662/CricBazzar%20Ecommerce/cricket-pads_qjpl23.jpg",
    rating: "3.5",
    description: "Large Size",
  },
  {
    _id: uuid(),
    productName: "Shirt and Trouser",
    price: "669",
    mrp: "749",
    offer: "11% OFF",
    categoryName: "CLOTHINGS",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921646/CricBazzar%20Ecommerce/cricket-clothing_mh8hsx.jpg",
    rating: "2",
    description: "Small Size",
  },
  {
    _id: uuid(),
    productName: "Shrey Cricket HAT",
    price: "570",
    mrp: "749",
    offer: "24% OFF",
    categoryName: "CLOTHINGS",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1648873566/CricBazzar%20Ecommerce/SHREY-PERFORMANCE-HAT-back-455x626__09158.1592687716_ncf5jb.jpg",
    rating: "2",
    description: "Large Size",
  },
  {
    _id: uuid(),
    productName: "Kookaburra Shoe",
    price: "899  ",
    mrp: "2250",
    offer: "60% off",
    categoryName: "SHOES",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921629/CricBazzar%20Ecommerce/cricket_shoe_v3mnpp.jpg",
    rating: "3.1",
    description: "With Spikes",
  },
  {
    _id: uuid(),
    productName: "TYKA CHAMP Shoes",
    price: "2994  ",
    mrp: "3742",
    offer: "20% off",
    categoryName: "SHOES",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1648874002/CricBazzar%20Ecommerce/3__80076.1646479134_re8rpc.jpg",
    rating: "4.3",
    description: "For Junior",
  },
  {
    _id: uuid(),
    productName: "SG - Thigh Guard",
    price: "525",
    mrp: "549",
    offer: "4% OFF",
    categoryName: "PROTECTION",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921671/CricBazzar%20Ecommerce/cricket-protection-kit_o6obky.png",
    rating: "4",
    description: "Good Protection",
  },
  {
    _id: uuid(),
    productName: "Kit Bag",
    price: "595",
    mrp: "1499",
    offer: "60% OFF",
    categoryName: "ACCESSORIES",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921622/CricBazzar%20Ecommerce/cricket_bags_r7olq7.jpg",
    rating: "1.5",
    description: "Gray Nicholls",
  },
  {
    _id: uuid(),
    productName: "Grip cone",
    price: "700",
    mrp: "1400",
    offer: "50% OFF",
    categoryName: "ACCESSORIES",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1648873357/CricBazzar%20Ecommerce/grip_cone__32187.1629749922_rnv2zh.jpg",
    rating: "3.9",
    description: "Kookaburra",
  },
  {
    _id: uuid(),
    productName: "Target Stump",
    price: "2000",
    mrp: "2500",
    offer: "20% OFF",
    categoryName: "ACCESSORIES",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1648874115/CricBazzar%20Ecommerce/1__00835_dclp03.webp",
    rating: "4.2",
    description: "GM SpringBak",
  },
];
