import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    productName: "Kookaburra Bat",
    price: "₹5,841",
    mrp: "₹6,499",
    offer: "10% OFF",
    categoryName: "CRICKET BATS",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921594/CricBazzar%20Ecommerce/Cricket-bat_lwscgk.jpg",
    rating: "4",
    description: "Extreme power",
  },
  {
    _id: uuid(),
    productName: "Leather Ball",
    price: "₹299",
    mrp: "₹699",
    offer: "57% OFF",
    categoryName: "CRICKET BALLS",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921638/CricBazzar%20Ecommerce/cricket-ball_lco1zt.jpg",
    rating: "4",
    description: "Standard Size",
  },
  {
    _id: uuid(),
    productName: "Batting Gloves",
    price: "₹435",
    mrp: "₹750",
    offer: "42% OFF",
    categoryName: "CRICKET GLOVES",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921655/CricBazzar%20Ecommerce/cricket-gloves_jswvvp.jpg",
    rating: "4",
    description: "Premium Quality",
  },
  {
    _id: uuid(),
    productName: "Adidas Batting Pads",
    price: "₹1,404",
    mrp: "₹1,499",
    offer: "6% OFF",
    categoryName: "CRICKET PADS",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921662/CricBazzar%20Ecommerce/cricket-pads_qjpl23.jpg",
    rating: "4",
    description: "Large Size",
  },
  {
    _id: uuid(),
    productName: "Shirt and Trouser",
    price: "₹669",
    mrp: "₹749",
    offer: "11% OFF",
    categoryName: "CRICKET CLOTHINGS",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921646/CricBazzar%20Ecommerce/cricket-clothing_mh8hsx.jpg",
    rating: "4",
    description: "Small Size",
  },
  {
    _id: uuid(),
    productName: "Kookaburra Shoe",
    price: "₹899  ",
    mrp: "₹2,250",
    offer: "60% off",
    categoryName: "CRICKET SHOES",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921629/CricBazzar%20Ecommerce/cricket_shoe_v3mnpp.jpg",
    rating: "4",
    description: "With Spikes",
  },
  {
    _id: uuid(),
    productName: "SG - Thigh Guard",
    price: "₹525",
    mrp: "₹549",
    offer: "4% OFF",
    categoryName: "PROTECTION GEAR",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921671/CricBazzar%20Ecommerce/cricket-protection-kit_o6obky.png",
    rating: "4",
    description: "Good Protection",
  },
  {
    _id: uuid(),
    productName: "Kit Bag",
    price: "₹595",
    mrp: "₹1,499",
    offer: "60% OFF",
    categoryName: "ACCESSORIES",
    img: "https://res.cloudinary.com/dgqwptcvp/image/upload/v1647921622/CricBazzar%20Ecommerce/cricket_bags_r7olq7.jpg",
    rating: "4",
    description: "Gray Nicholls",
  },
];
